server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:tomcat.keystore
    key-store-type: JKS
    key-password: 1008wuxing
    key-store-password: 1008wuxing
    key-alias: tomcat


spring:
  datasource:
    username: root
    password: 2023Aii1008
    url: jdbc:mysql://47.102.104.144:3306/interview?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    port: 6379
#    host: localhost
  # 修改SpringBoot允许上传的单个文件的大小（默认1MB）
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.example: debug


mybatis-plus:
  mapper-locations: classpath:mapper.*/*.xml    # 扫描所有mybatis的xml文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# https